### ISSUE TITLE
UIButton are not responding to events

### ISSUE THREAD

**Issue by wasappi** [blackmirror-media/BMPickerModal#9]
Hi, 
Save and cancel buttons selectors are not triggered on iPhone. (iOS 11) 
Any idea on what could be the issue ? Something strange with the responder chain when added on uiwindow ?

**Comment by wasappi** [comment]
No more luck if I try to add a UISwitch to the view, no events are trigerred

**Comment by eriadam** [comment]
Hello, Thanks for the feedback. The trick is to create a stored property for your control. Then then the button actions should work fine. I updated the docs and added an example project to the project as well.


```swift
import UIKit
import BMPickerModal

class ViewController: UIViewController {

  var datePickerModal: BMPickerModal?

  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)

    self.datePickerModal = BMPickerModal()
    self.datePickerModal?.mode = .datePicker

    self.datePickerModal?.show { selectedDate in
      print(selectedDate)
      // Do something with the date here
    }
  }
}

```

**Comment by wasappi** [comment]
Hi Adam, that did the trick ! I'm still not completly sure what happened behind the curtains when declaring the object inside my function vs your stored property example.
Thanks!
